#!/usr/bin/env ruby

require 'fileutils'
include FileUtils

if ARGV.first == 'new' && ARGV[1]
  puts "Making new Whales App:"
  app_name = ARGV[1]
  display = {verbose: true}

  mkdir_p '/usr/local/bin'
  ln_s pwd + '/whales', '/usr/local/bin'

  cd '..'
  mkdir app_name, display
  cd app_name
  touch "routes.rb", display
  File.open("routes.rb", 'w') do |f|
    f.write <<-TEXT
require_relative '../whales/whales_actions/lib/whales_controller/base'

def make_router
  router = WhalesDispatch::Router.new

  router.draw do
    # include routes using this syntax:
    # get Regexp.new("^/users/new$"), UsersController, :new
  end

  router
end
    TEXT
  end

  touch "whales", display
  File.open("whales", 'w') do |f|
    f.write <<-TEXT
#!/usr/bin/env ruby

require_relative '../whales/whales'
require_relative './routes'
require_relative './config/database.rb'

scripts(make_router)\n
    TEXT
  end

  chmod "+x", "whales"
  ln_s pwd + '/whales', '/usr/local/bin'

  touch "Gemfile", display
  File.open("Gemfile", "w") do |f|
    f.write <<-TEXT
source 'https://rubygems.org'\n
    TEXT
  end

  mkdir "config", display
  touch "config/database.rb", display
  File.open("config/database.rb", "w") do |f|
    f.write <<-TEXT
require_relative '../../whales/whales_orm/lib/db_connection.rb'

# https://tomafro.net/2010/01/tip-relative-paths-with-file-expand-path
ROOT_FOLDER = File.join(File.dirname(__FILE__), '../db')

# sql file name goes here, the default is database.sql
SQL_FILE = File.join(ROOT_FOLDER, 'database.sql')

# Here you can configure where you want the database file to be saved
DB_FILE = File.join(ROOT_FOLDER, 'database.db')
    TEXT
  end

  mkdir "db", display
  touch "db/database.sql", display

  mkdir_p 'app/controllers', display

  touch "app/controllers/application_controller.rb", display
  File.open("app/controllers/application_controller.rb", "w") do |f|
    f.write <<-TEXT
require_relative '../../../whales/whales_actions/lib/whales_controller/base'
require_relative '../../config/database.rb'

class ApplicationController < WhalesController::Base
end
    TEXT
  end

  cd 'app'
  mkdir 'models', display
  mkdir 'views'

end
