#!/usr/bin/env ruby

require 'fileutils'
include FileUtils

if ARGV.first == 'new' && ARGV[1]
  puts "Making new Whales App:"
  app_name = ARGV[1]
  display = {verbose: true}

  cd '..'
  mkdir app_name, display
  cd app_name
  touch "routes.rb"
  File.open("routes.rb", 'w') do |f|
    f.write <<-TEXT
require_relative '../../../whales/whales_actions/lib/base'
WhalesDispatch::Router.new.draw do


end\n
    TEXT
  end

  mkdir_p 'app/controllers', display
  cd 'app'
  mkdir 'models', display
  mkdir 'views', display

end
